# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 06:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=120, null=True)),
                ('lastname', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('background', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='description default text', null=True)),
                ('pic', models.ImageField(default='pic/scientist.jpg', upload_to='pic/')),
                ('is_staff', models.BooleanField(default=False)),
                ('institution', models.CharField(blank=True, help_text='Where do you work?', max_length=200, null=True)),
                ('inst_url', models.URLField(blank=True, help_text='URL to the homepage of your company', null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='InstructorProfile',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
