# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_auto_20161126_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pic',
            new_name='facepic',
        ),
        migrations.AddField(
            model_name='profile',
            name='bg_pic',
            field=models.ImageField(default='background/default_bg.jpg', upload_to='background/'),
        ),
    ]
