# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QandA', '0001_initial'),
        ('Profiles', '0004_auto_20161127_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='answers',
            field=models.ManyToManyField(to='QandA.Answer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='questions',
            field=models.ManyToManyField(to='QandA.Question'),
        ),
    ]
