# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='Attention', max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
